module IME
  module Collection
    class Entry[T]
      attr_reader yomi: String
      attr_reader kaki: String
      attr_reader category: T
      def initialize: (String yomi, String kaki, T category) -> void
    end
  end
end
