module IME
  module SKK
    type entry = IME::Collection::Entry[nil]

    def self.convert: (Enumerable[personal] src) -> Enumerable[entry]
    def self.write_file: (Enumerable[entry] src, Pathname path) -> void
    def self.convert_person: (personal person) -> Enumerable[entry]
    def self.pair_to_entry: (pair | nil pair) -> entry?
  end
end
