#
# rubocop.yml
#
# These codes are licensed under CC0.
# http://creativecommons.org/publicdomain/zero/1.0/deed.ja
#

require:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  Exclude:
    - "vendor/**/*"
    - "bin/**"
    - "tmp/**/*"
    - "node_modules/**/*"
    - ".git/**/*"
  NewCops: enable

Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false