require:
  - rubocop-minitest

AllCops:
  Exclude:
    - "vendor/**/*"
    - "bin/**"
    - "tmp/**/*"
    - "node_modules/**/*"
    - ".git/**/*"
  NewCops: enable

Style/Documentation:
  Enabled: false
