class Changelog
  @lines: Array[String]

  PATTERN_VERSION_LINE: Regexp
  PATTERN_LABEL_LINK: Regexp

  def initialize: (Pathname) -> void
  def first_line: -> String
  def enum_version_lines: -> Array[String]
  # TODO: nilは来ないはずなので回避方法を探す
  def enum_versions: -> Array[String | nil]
  def enum_type_lines: -> Array[String]
  def enum_link_label_definitions: -> Array[String]
  def link_label_dict: -> Hash[String, String]
  def enum_version_sections: -> Hash[String, Array[String]]

  private

  def version_section_parser: (String | nil, String) -> [String | nil, String | nil]
end
