#
# pull_request.yml
#
# These codes are licensed under CC0.
# http://creativecommons.org/publicdomain/zero/1.0/deed.ja
#

name: check
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check_and_build:
    name: lint/typecheck/unittest/build
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 1
      - name: setup ruby
        uses: ruby/setup-ruby@v1.61.0
        with:
          bundler-cache: true
      - name: format check
        run: bundle exec rubocop
      - name: type check
        run: bundle exec steep check
      - name: unittest
        run: bundle exec rake test
      - name: build
        run: bundle exec rake
      - name: upload artifact
        uses: actions/upload-artifact@v2.2.1
        with:
          name: ime_dictionary
          path: build/*.txt
