#
# release.yml
#
# These codes are licensed under CC0.
# http://creativecommons.org/publicdomain/zero/1.0/deed.ja
#

name: release
on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 1
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1.90.0
        with:
          bundler-cache: true
      - name: Build
        run: bundle exec rake
      - name: Get Version from Tag
        id: tag_name
        run: |
          echo ::set-output name=current_version::${GITHUB_REF#refs/tags/v}
        shell: bash
      - name: Get Changelog Entry
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v2
        with:
          version: ${{ steps.tag_name.outputs.current_version }}
          path: ./CHANGELOG.md
      - name: Rename Files to Add Version
        run: |
          rename.ul .txt _v${{ steps.changelog_reader.outputs.version }}.txt build/*.txt
          mv build/SKK-JISYO.magica build/SKK-JISYO.magica.v${{ steps.changelog_reader.outputs.version }}
      - name: List Build Files
        run: |
          ls ./build/*
      - name: Create Release and Upload Assets
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.tag_name.outputs.current_version }}
          name: v${{ steps.tag_name.outputs.current_version }}
          body: ${{ steps.changelog_reader.outputs.changes }}
          draft: false
          prerelease: false
          files: "./build/*"
