#
# snapshot.yml
#
# These codes are licensed under CC0.
# http://creativecommons.org/publicdomain/zero/1.0/deed.ja
#

name: snapshot
on:
  push:
    branches:
      - main

jobs:
  snapshot:
    name: build and save snapshot
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 1
      - name: setup ruby
        uses: ruby/setup-ruby@v1.61.0
        with:
          bundler-cache: true
      - name: build
        run: bundle exec rake
      - name: gitattributes
        run: | 
          cat <<EOF > build/.gitattributes
          magica_ime_data_MSIME.txt encoding=UTF-16LE-BOM eol=crlf
          magica_ime_data_ATOK.txt encoding=UTF-16LE-BOM eol=crlf
          magica_ime_data_Mac.txt encoding=UTF-8 eol=lf
          magica_ime_data_GoogleIME.txt encoding=UTF-8 eol=crlf
          EOF
      - name: snapshot
        uses: s0/git-publish-subdir-action@v2.4.0
        env:
          REPO: self
          BRANCH: snapshot
          FOLDER: build
          MESSAGE: "snapshot for {sha}\n---\n{msg}"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
